In [1]:
import numpy as np

A= np.array([[1,2],[0,1],[2,3]])
v = np.array([[2],[6]])
print(np.dot(A,v))

[[14]
 [ 6]
 [22]]


In [2]:
print(np.dot(v,A))

ValueError: shapes (2,1) and (3,2) not aligned: 1 (dim 1) != 3 (dim 0)

In [4]:
B = np.array([[2,5],[6,7]])

In [5]:
print(np.dot(A,B))

[[14 19]
 [ 6  7]
 [22 31]]


In [6]:
print(np.dot(A,np.transpose(A)))

[[ 5  2  8]
 [ 2  1  3]
 [ 8  3 13]]


In [7]:
print(np.dot(np.transpose(A),A))

[[ 5  8]
 [ 8 14]]


In [8]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
print(np.dot(A,np.transpose(A)))

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [10]:
print(np.dot(np.transpose(A),A))


[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [11]:
from numpy import linalg as LA

v=np.array([3,4])
LA.norm(v)


5.0

In [12]:
np.dot(v,np.transpose(v))

25

In [17]:
def find_distance(a,b):

    return LA.norm(a-b)



In [19]:
a = np.array([1,1])
b = np.array([2,2])
c = np.array([3,8])
blue = find_distance(a,b)
print(blue)

1.4142135623730951


In [20]:
green = find_distance(b,c)
orange = find_distance(a,c)

print(green)
print(orange)

6.082762530298219
7.280109889280518
